### ISSUE TITLE
Close MVP Func Specs

### ISSUE THREAD

**Issue by andydobrucki** [Timeqube/core#14]
What should it do in the MVP

**Comment by andydobrucki** [comment]
Write a doc that follow these chapters:

Goals
User Personas
User Interactions and Functions
Wireframes 
Non-Functional Requirements
Risks
Future Iterations

**Comment by andydobrucki** [comment]
https://docs.google.com/document/d/1q8732lV6M3ETZOYVTHPiw7xMvg_vATRiJUi1kyfSlWg/edit?usp=sharing

**Comment by skbnm** [comment]
fixed some minor grammar things + added comms

**Comment by andydobrucki** [comment]
MVP spec iter done

**Comment by andydobrucki** [comment]
add hw / sw changes needed
