### ISSUE TITLE
Validation Form & Questions

### ISSUE THREAD

**Issue by andydobrucki** [Timeqube/core#18]

**Comment by andydobrucki** [comment]
Questions:

- Do you feel like office meetings are often ineffective?
-  Would Timeqube help your business make meetings time-effective?
- 3% from every Timeqube purchase goes to helping MS patients worldwide. Would this information be important to your business' CSR Activity?
- How much would you pay for one Timeqube?
- Company Name (optional)
- Email (optional)

**Comment by andydobrucki** [comment]
@Mindgames @skbnm  please iterate

**Comment by skbnm** [comment]
I would only delete the "often" from the first sentence, as this is a classic "question with a thesis already inserted", besides that, cool

**Comment by skbnm** [comment]
Maybe we should incentivize people to leave the email with some discount/bonus for the final product?

**Comment by andydobrucki** [comment]
https://goo.gl/jRAjc8

**Comment by andydobrucki** [comment]
@Mindgames thanks for comments . Fixed deck footer and form according to your notes.

**Comment by andydobrucki** [comment]
bit.ly/timeqube-b2b is the sharable link for deck + linked form in the footer
