### ISSUE TITLE
Google analytics

### ISSUE THREAD

**Issue by Mindgames** [Timeqube/core#57]
Create account for  GA & Webmaster tools and give me access

**Comment by andydobrucki** [comment]
tracking snippet : 
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-118994195-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-118994195-1');
</script>

**Comment by andydobrucki** [comment]
Rights granted for m@timeqube.com @Mindgames
