### ISSUE TITLE
API Key freshmail

### ISSUE THREAD

**Issue by Mindgames** [Timeqube/core#66]
Need API key for freshmail

**Comment by andydobrucki** [comment]
Created new account with andy@timeqube.com
granted admin access for m@ingridx.com (tq.com doesn't work, probably added that @ with previous FM account I can't access cause mfks blocked it again)

API/Sec:
b667070e339b177a51c6fc6923ae51dc
5ea540553d4859a19ead14f6346f7a9fa8e56a13

**Comment by andydobrucki** [comment]
@Mindgames
