### ISSUE TITLE
Improve Roadmap / Vision

### ISSUE THREAD

**Issue by andydobrucki** [Timeqube/core#8]

**Comment by andydobrucki** [comment]
https://docs.google.com/spreadsheets/d/1hgnzqCdPMJz8ULb2i03g4AIARi4F8FvrHjX8DmppIJM/edit?usp=sharing

**Comment by andydobrucki** [comment]
I'll need to pick your brains and think of ANY even wildest functionality we can get . Data driven. Best if we can use BT/WIFI/MIC and diff integrations. What can we give to enterprises based on data analysis from the qube? what can we report? what data can we collect?

**Comment by andydobrucki** [comment]
Would be cool to have a project roadmap e.g. investor readiness, b2b marketing readiness, funded, first prototype ready etc

**Comment by skbnm** [comment]
- I'm not sure if we need presets in the first version - if user can easily set their time of choice it is more straightforward, whereas any presets and short/long taps makes it more complicated to use
- By exchange do you mean a place to pick your charity of choice?
- Is microphone necessary? Im just wondering that people rarely make recordings of their meetings, it can spook out some of the corporates info security departments and also makes the use case a little more foggy (i.e. it almost act like a corporate stationary phone for handling conf calls)
