### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by Mindgames** [Timeqube/core#9]
Build and launch website

**Comment by Mindgames** [comment]
@andydobrucki  What section you suggest on website

- Email signup

**Comment by andydobrucki** [comment]
@Mindgames https://docs.google.com/presentation/d/1sAhwpItshy03zlhKIDPuLy97SjKVTXEj6ug5kjniFDo/edit#slide=id.p

**Comment by andydobrucki** [comment]
http://188.166.146.76/
